
variants:
    common7: &vCommon7
        bcmath: ~
        bz2: ~
        calendar: ~
        ctype: ~
        curl: ~
        embed:
            - '--enable-embed=shared'
        exif: ~
        fileinfo: ~
        filter: ~
        fpm: ~
        ftp: ~
        gd:
            - '--with-gd'
            - '--with-jpeg-dir=/usr'
            - '--with-png-dir=/usr/lib'
            - '--with-xpm-dir=/usr/lib'
        gmp:
            - ''
        gettext: ~
        hash: ~
        iconv: ~
        intl:
            - '--enable-intl'
        json: ~
        mbstring: ~
        mhash: ~
        openssl:
            - '--with-openssl'
            - '--with-openssl-dir=/usr/lib/ssl1.0'
        phar: ~
        pdo: ~
        mysql:
            - 'ac_cv_decimal_fp_supported=no'
            - '--with-mysqli'
            - '--with-pdo-mysql'
        pgsql: ~
        soap: ~
        sqlite: ~
        xmlrpc: ~
        zip:
            - '--enable-zip'
        zlib:
            - '--with-zlib'
        dbg:
            - '--enable-phpdbg'
        opcache:
            - '--enable-opcache'

    common701: &vCommon701
        <<: *vCommon7

    common702: &vCommon702
        <<: *vCommon7
        sodium:
            - '--with-sodium'

    common703: &vCommon703
        <<: *vCommon7
        sodium:
            - '--with-sodium'

    # The "+common702-zts" does not work :-(
    # It has to be added as an extra option.
    common702-zts:
        zts:
            - '--enable-maintainer-zts --with-tsrm-pthreads'

extensions:

    ext-igbinary-7: &ext-igbinary-7
        igbinary: >-
            3.0.1

    ext-imagick-7: &ext-imagick-7
        imagick: >-
            3.4.4

    ext-inotify-7: &ext-inotify-7
        inotify: >-
            stable

    ext-memcached-7: &ext-memcached-7
        memcached: >-
            3.1.3
            --
            --enable-memcached-sasl
            --enable-memcached-session
            --enable-memcached-igbinary
            --enable-memcached-json
            --enable-memcached-msgpack

    ext-mongodb-7: &ext-mongodb-7
        mongodb: >-
            1.5.3

    ext-msgpack-7: &ext-msgpack-7
        msgpack: >-
            stable

    ext-pcntl-7: &ext-pcntl-7
        pcntl: >-
            stable

    ext-posix-7: &ext-posix-7
        posix: >-
            stable

    ext-psr-7: &ext-psr-7
        psr: >-
            0.6.0

    ext-pthreads-7: &ext-pthreads-7
        pthreads: >-
            3.1.6

    ext-readline-7: &ext-readline-7
        readline: >-
            stable

    ext-redis-7: &ext-redis-7
        redis: >-
            4.3.0
            --
            --enable-redis-igbinary
            --enable-redis-session
            --enable-redis-lzf

    ext-xdebug-7: &ext-xdebug-7
        xdebug: >-
            2.6.1

    ext-xdebug-703: &ext-xdebug-703
        xdebug: >-
            2.7.2

    ext-yaml-7: &ext-yaml-7
        yaml: >-
            2.0.4

    common7: &eCommon7
        <<: *ext-igbinary-7
        <<: *ext-msgpack-7
        <<: *ext-pcntl-7
        <<: *ext-posix-7
        <<: *ext-psr-7
        <<: *ext-imagick-7
        <<: *ext-inotify-7
        <<: *ext-mongodb-7
        <<: *ext-xdebug-7
        <<: *ext-yaml-7
        <<: *ext-redis-7
        <<: *ext-memcached-7

    common701:
        <<: *eCommon7

    common702:
        <<: *ext-readline-7
        <<: *eCommon7

    common703:
        <<: *ext-readline-7
        <<: *ext-xdebug-703
        <<: *eCommon7
